# Use the official image as a parent image.
FROM ubuntu:19.10

# Set the working directory.
WORKDIR /linaro-android

ADD sources.list-19.10 /etc/apt/sources.list
#RUN sed -i  's|deb |deb [arch=arm64,armhf] |' /etc/apt/sources.list
#RUN cat sources.list > /etc/apt/sources.list
RUN apt-get update && apt install -y qemu-user-static binfmt-support && dpkg --add-architecture amd64 && apt install -y libc6:amd64

RUN apt-get update && apt-get install -y apt-utils unzip wget git sudo usbutils curl tar xz-utils libcurl4 coreutils zip python-lxml python-setuptools python-pexpect aapt lib32z1-dev libc6-dev-i386 lib32gcc1 python-dev python-protobuf protobuf-compiler python-virtualenv python-pip python-pexpect psmisc openjdk-8-jdk-headless openjdk-11-jdk-headless

#RUN apt-get install libc6:i386 libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386

# https://developer.android.com/studio/releases/platform-tools
ADD https://dl.google.com/android/repository/platform-tools_r28.0.0-linux.zip .
RUN unzip platform-tools_r28.0.0-linux.zip
RUN rm -f /usr/bin/fastboot /usr/bin/adb && ln -s /linaro-android/platform-tools/fastboot /usr/bin/fastboot && ln -s /linaro-android/platform-tools/adb /usr/bin/adb
